name: d_notes_app
description: "Untuk memenuhi submission proyek akhir course Dicoding: Belajar Membuat Aplikasi Flutter untuk Pemula"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0-130.0.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  path: ^1.8.2

flutter:
  uses-material-design: true
